stages:
  - build_binary
  - build_docker_image
  - test
  - deploy

variables:
  DOCKER_REPOSITORY: "atarax"
  CANDIDATE_IMAGE: "$DOCKER_REPOSITORY/${CI_PROJECT_NAME}:candidate-${CI_COMMIT_SHA}"
  STABLE_IMAGE: "${CI_PROJECT_NAME}:${CI_COMMIT_SHA}"

build_binary:
  image: golang 
  stage: build_binary
  artifacts:
    paths:
      - bin
  script:
    # - export GOPATH='/go'
    # - mkdir -p /go/src/github.com/atarax/kraken
    # - cd /go/src/github.com/atarax/ 
    # - git clone https://github.com/atarax/kraken
    # - cd kraken
    - go get ./...
    - CGO_ENABLED=0 go build -o bin/kraken

build_docker_image:
  stage: build_docker_image
  dependencies:
    - build_binary
  script:
    - docker build . -t $CANDIDATE_IMAGE
    - docker push $CANDIDATE_IMAGE

test:
  stage: test
  script:
    - "echo hello"

deploy:
  stage: deploy
  script:
    - echo "hello"