stages:
  - build
  - test
  - deploy

variables:
  DOCKER_REPOSITORY: ""
  CANDIDATE_IMAGE: "${CI_PROJECT_NAME}:candidate-${CI_COMMIT_SHA}"
  STABLE_IMAGE: "${CI_PROJECT_NAME}:${CI_COMMIT_SHA}"

build:
  image: golang 
  stage: build
  script:
    - export GOPATH='/go'
    - mkdir -p /go/src/github.com/atarax/rbl-control
    - cd /go/src/github.com/atarax/ 
    - git clone https://github.com/atarax/rbl-control
    - cd rbl-control
    - go get ./...
    - CGO_ENABLED=0 go build -o bin/rbl-control
test:
  stage: test
  script:
    - "echo hello"

deploy:
  stage: deploy
  script:
    - echo "hello"